[app]
elf = "vario.elf"
addr_start = 0x0800_0000
addr_max = 0x0807_ffff

[copy]
elf = "assets/copy_stm32h743_1m.elf"
addr_start = 0x0810_1000
addr_max = 0x0810_ffff

[image]
name = "image.bin"
addr_storage = 0x0810_0000
hw_version = "1.0.0"
sw_version = "0.1.0.0"
